#!/bin/sh
set -e

export INCUS_DOCUMENTATION=/usr/incus/doc/
export INCUS_LXC_HOOK=/usr/incus/share/lxc/hooks/
export INCUS_LXC_TEMPLATE_CONFIG=/usr/incus/share/lxc/config/
export INCUS_AGENT_PATH=/usr/incus/agent/
export INCUS_EDK2_PATH=/usr/incus/share/qemu/
export INCUS_UI=/usr/incus/ui/
export LD_LIBRARY_PATH=/usr/incus/lib/
export PATH=/usr/incus/bin/:${PATH}
export HOME=/var/lib/incus/

mkdir -p /var/log/incus/
exec incusd "$@"
